baseURL: /
languageCode: en-us
title: RRR
subtitle: Reduce Recycle Recode
theme: terminal

copyright: '@ Nikko Miu'

params:
  themeColor: pink
  centerTheme: true
  noindex: true

  # automatically set the cover image from cover.(jpg|png|webp)
  autoCover: true
  # show reading time by default
  readingTime: true

  logo:
    logoText: Reduce Recycle Recode
