baseURL: /
languageCode: en-us
title: RRR

disableHugoGeneratorInject: true
copyright: Nikko Miu

module:
  mounts:
    - source: static
      target: static
    - source: "node_modules/katex/dist/fonts"
      target: "static/css/fonts"

security:
  funcs:
    getenv:
      - ^CF_PAGES

menu:
  main:
    - name: Posts
      weight: 1
      url: /posts/
    - name: Notes
      weight: 2
      url: /notes/
    - name: Guides
      weight: 3
      url: /guides/
  footer:
    - name: Home
      weight: 1
      url: /
    - name: Posts
      weight: 2
      url: /posts/
    - name: Notes
      weight: 3
      url: /notes/
    - name: Guides
      weight: 4
      url: /guides/
    - name: Authors
      weight: 5
      url: /authors/
    - name: Categories
      weight: 6
      url: /categories/
    - name: Tags
      weight: 7
      url: /tags/

markup:
  highlight:
    style: modus-vivendi

params:
  subtitle: Reduce, Recycle, Recode

  gitRepoURL: https://github.com/nikkomiu/blog
  gitDefaultBranch: main

  centerTheme: true
  noindex: true

  readMore: Continue Reading
  noPostsMessage: There are no %s 😭

  # automatically set the cover image from cover.(jpg|png|webp)
  autoCover: true
  # show reading time by default
  readingTime: true

  logo:
    logoText: Reduce Recycle Recode
