name: Page Issue
description: Report an issue with a page on the site
labels: ["page"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help us understand the issue you're reporting.
  - type: input
    id: page_url
    attributes:
      label: Page URL
      description: The URL of the page where you encountered the issue
      placeholder: https://example.com/page
    validations:
      required: true
  - type: textarea
    id: issue_description
    attributes:
      label: Issue Description
      description: Describe the issue you encountered
      placeholder: What went wrong?
    validations:
      required: true
