name: Page Issue
description: Report an issue with a page on the site
labels: ["page"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help us understand the issue you're reporting.
  - type: input
    id: page_url
    attributes:
      label: Page URL
      description: The URL of the page where you encountered the issue
      placeholder: https://example.com/page
    validations:
      required: true
  - type: input
    id: commit_sha
    attributes:
      label: Commit SHA of Site
      description: The Git Commit SHA of the site at the time of the issue
      placeholder: a2ccd68631106073761255d1c9c444fc088b45e7
    validations:
      required: false
  - type: textarea
    id: issue_description
    attributes:
      label: Issue Description
      description: Describe the issue you encountered
      placeholder: What went wrong?
    validations:
      required: true
