name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Prettier
        run: npm run prettier:check

      - name: Stylelint
        run: npm run stylelint:check

      - name: Markdownlint
        run: npm run markdownlint:check
